### ISSUE TITLE
Add settings

### ISSUE THREAD

**Issue by she-freak** [crdroidandroid/android_packages_apps_DocumentsUI#1]
Add settings and at least minimal customization of the file manager. There is no way to change the initial tab "Downloaded" to any other. You have to take extra steps to open the desired directory. I agree, you can use any other file manager, but for each sneeze the default one opens and there is no way to disable the default manager. More precisely, you can, but it kills the file system.

**Comment by gwolf2u** [comment]
using AOSP feel for it
